Update Kong example for MutualTLS SecurityScheme
OAI v3.1 includes a new securityScheme to define
Mutual TLS authentication. Kong example requires
v3.1 definition, but bundling the specfiles only
supports v3.0.

diff --git a/examples/kong/start b/examples/kong/start
--- a/examples/kong/start
+++ b/examples/kong/start
@@ -24,18 +24,28 @@ else
     announce "Reloading Kong config"
     docker exec kong kong reload
 fi
+sleep 10
+
+announce "Ensure Kong Gateway is active"
+if [[ -z $(curl -s http://localhost:8001/services/Conjur | grep '"name":"Conjur"') ]]; then
+    echo "Kong setup failed"
+    exit 1
+else
+    echo "Kong setup successful"
+fi
 
 announce "Making requests to Conjur through Kong Gateway"
 
 ensure_conjur_up
+sleep 10
 admin_api_key="$(docker-compose exec -T conjur conjurctl role retrieve-key dev:user:admin | tr -d '\r')"
-token="$(curl http://localhost:8000/authn/dev/admin/authenticate \
+token="$(curl -s http://localhost:8000/authn/dev/admin/authenticate \
     --header "Accept-Encoding: base64" \
     --data $admin_api_key)"
 
 secret_data="Hello World!"
 
-curl -i http://localhost:8000/secrets/dev/variable/testSecret \
+curl -is http://localhost:8000/secrets/dev/variable/testSecret \
     -H "Authorization: Token token=\"$token\"" \
     --data "$secret_data"
 
